# Generated by Django 4.2.26 on 2026-07-08 12:33

from django.db import migrations, models
import django.db.models.deletion
import signals.apps.publiclog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0202_alter_question_field_type_alter_status_target_api_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_network', models.CharField(help_text='Use an IP address or CIDR range, for example 203.0.113.10 or 203.0.113.0/24.', max_length=64, unique=True, validators=[signals.apps.publiclog.models.validate_ip_network])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('ip_network',),
            },
        ),
        migrations.CreateModel(
            name='ReporterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_log', to='signals.signal')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
